### ISSUE TITLE
On-device symbolication - security risk?

### ISSUE THREAD

**Issue by donnie-jp** [ChimeHQ/Meter#1]
Hi,
The project looks like it could be really cool, and useful! 👍 
I'm also interested in how MetricKit can enable end-to-end performance tracking.

You mentioned that you intend to do on-device symbolication. Isn't there a security risk with that? I think it will make it easier to reverse-engineer the binary if a `bad person` gets hold of a device. OWASP mentions that [here](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06c-Reverse-Engineering-and-Tampering.md#debugging-release-apps). Perhaps I missed something.

Cheers

**Comment by mattmassicotte** [comment]
Thanks for the question!

I don't think there is any reason to be concerned. On-device symbolication is just the process of using information that is **already present** in the executables on-disk to map addresses back to symbol names. The tools listed in the document you reference can already do this, and because they have access to both on- and off-device resources, can do it far better.

**Comment by donnie-jp** [comment]
Thanks for the reply!
Is the reason the information is already present in the executables that the symbol names haven't been stripped (which wouldn't be typical of a Release build) from the binary? Usually a dSYM file needs to be uploaded to the service doing the symbolicating so having the real symbols on the device means it's easier for someone to reason about what each method is doing. If I still have the wrong end of the stick I apologize and feel free to ignore me 😅

**Comment by mattmassicotte** [comment]
No no, very good follow up questions!

Symbolic information can come from many sources, and isn't all of the same fidelity. It's possible to look up public symbols in a dylib, even one that has been stripped, because that's what the linker needs to do at runtime. I'm less familiar with the internals here, but this is what I was planning to investigate using for symbolication. So, a dSYM definitely is not required for symbolication. You'll never have access to the dSYMs for Apple's libraries, and you still would like to see symbols for those frames in your stack traces.

(Aside: the symbolication system Apple uses for crash reports within Xcode actually **does** symbolicate Apple's libraries against real dSYMs. You can actually see file/line info for Apple's libraries in your reports! I was surprised they do this, but and it might change in the future.)

Now you are right that it's better to use a dSYM. A dSYM includes huge amounts of other meta data about your code to enable full debugging. This makes them ideal for symbolication, because besides being authoritative on symbols, they also include file/line information. Exposing the dSYM of your executables ** definitely is** a big security risk because it makes reverse-engineering much easier.

My hope is that there's enough runtime information to provide a reasonable amount of symbols for **Apple's** libraries on-device. Those are the most challenging for end-users to symbolicate anyways. Then, a second step will probably be necessary to fill the frames from the app itself.

**Comment by donnie-jp** [comment]
Ah, ok, I understand what you meant a bit better now!
Can you recommend any links about that dSYM-less on-device symbolication idea?

**Comment by mattmassicotte** [comment]
I'm afraid I don't know of any documentation on the subject. There is probably a fair amount of stuff written on Mach-O, the executable format. I'm reasonably familiar with it at a high level, but have never interacted with the symbol tables and/or Obj-C information.
